### ISSUE TITLE
`Combined Mesh (root: scene)` is not readable

### ISSUE THREAD

**Issue by lchojnack** [autowarefoundation/AWSIM-Labs#49]
During the setup of the AWSIM, I encountered the issue in the screenshot below. I've downloaded the Nishinjuku unitypackage from [here](https://autowarefoundation.github.io/AWSIM/main/GettingStarted/SetupUnityProject/#:~:text=Download%20and%20import%20Nishishinjuku_urp.unitypackage)

![image](https://github.com/autowarefoundation/AWSIM/assets/8416175/f6590098-f828-426e-aa25-81047f239430)

As suggested, I've unmarked the scene as static, and the issue doesn't appear. 

---

I've noticed that the root cause of the issue is related to the `Shrub_Facets01_Index01_Geo01`, `ShrubPlanter_Facets01_Index01_Geo01`, `ShrubZenrin_Facets01_Index01_Geo01` objects. 

When they are marked as static, then the mesh after clicking `Play` is changing to `Combined Mesh (root: scene)`, and issue appears.
When they are not marked as static, then the object's mesh is not changing and the issue doesn't appear. 

https://github.com/autowarefoundation/AWSIM/assets/8416175/29df61f6-bc23-4375-9c1a-a0494620124a

**Comment by xmfcx** [comment]
Bug cause:

https://github.com/autowarefoundation/AWSIM/blob/6416d22d76abdfc5d5fb57df9099904036e28356/Assets/RGLUnityPlugin/Scripts/LowLevelWrappers/RGLMeshObject.cs#L96-L100

Here it attempts to read the mesh of the combined mesh but it fails.

But this happens only for these shrubs (at least at the spawn).

![Screenshot from 2024-04-16 16-49-08](https://github.com/autowarefoundation/AWSIM/assets/10751153/ff0e1763-dac8-4926-8637-46f94e6c62d3)

When I unmark the "Static" checkbox for these shrubs, then, the issue goes away.

But we have many more objects like large buildings marked as static, why are they not causing problems?

Then I realized, buildings retain their original meshes on the play mode. But shrubs' meshes change.

### Mesh in stopped editor

![Screenshot from 2024-04-16 16-49-21](https://github.com/autowarefoundation/AWSIM/assets/10751153/a9e2fc46-1a0c-4d04-a3d3-075f4bc01606)

The object has the normal mesh.

### Mesh in playing editor

![Screenshot from 2024-04-16 16-49-52](https://github.com/autowarefoundation/AWSIM/assets/10751153/9b111c8a-08d6-45df-8269-40c06b3685a7)

The object has the combined mesh.

## Why?

It turns out, with ["Static Batching"](https://docs.unity3d.com/Manual/static-batching.html) some of the mesh data is combined into one and the combined mesh's vertices cannot be read like the others, probably some code update would be needed to handle such objects from the https://github.com/RobotecAI/RobotecGPULidar side.

And not everything gets their meshes optimized. So, I will create a PR to disable static batching from the player settings and things should keep working.

Later on some other optimization methods can be explored.

cc. @lchojnack @mozhoku
